Selenium
infuse-training-aug-2023/practice-MADHURA pull request #4
Opened 2023-08-23 08:27 UTC by madhura0404

2023-08-23 09:16 UTC, joyrel-vaz requested changes

2023-08-23 09:16 UTC, joyrel-vaz commented on selenium/6.rb
> +dropdown.click
This step is not required

2023-08-23 09:16 UTC, joyrel-vaz commented on selenium/6.rb
> +puts dropdown.text
A better approach is to use

`dropdown = Selenium::WebDriver::Support::Select.new(dropdown_xpath_element)`

You should make use of the functions mentioned here: https://www.selenium.dev/selenium/docs/api/rb/Selenium/WebDriver/Support/Select.html

2023-08-23 09:16 UTC, joyrel-vaz commented on selenium/9.rb
> +table_header= driver.find_elements(:tag_name, 'h3')
`h3` is not a good locator to get table header. Use `tr` instead.

2023-08-23 09:16 UTC, joyrel-vaz commented on selenium/10.rb
> +    if columns.size > column_index
Why is this check done?

2023-08-23 09:16 UTC, joyrel-vaz commented on selenium/11.rb
> +    if column_index < cells.size
Why is this check done?

2023-08-23 09:16 UTC, joyrel-vaz commented on selenium/11.rb
> +if row_index < rows.size
Why is this check done?

2023-08-23 09:16 UTC, joyrel-vaz commented on selenium/12.rb
> +checkout.click
Code can be modularised into methods performing different test flows

2023-08-23 11:59 UTC, madhura0404 commented on selenium/11.rb
> +    if column_index < cells.size
it is done to check if the row_index and column_index is not greater than the no. of rows / columns in the table.

2023-08-23 11:59 UTC, madhura0404 commented on selenium/11.rb
> +if row_index < rows.size
it is done to check if the row_index and column_index is not greater than the no. of rows / columns in the table.

2023-08-23 19:41 UTC, madhura0404 commented on selenium/11.rb
> +    if column_index < cells.size
But i think I should have used 'else' to print error

2023-08-23 19:42 UTC, madhura0404 commented on selenium/11.rb
> +if row_index < rows.size
But i think I should have used 'else' to print error

2023-08-28 16:49 UTC, madhura0404 commented on selenium/10.rb
> +    if columns.size > column_index
it is done to check if the column_index is not greater than the no. of columns in the table.

2024-04-10 11:29 UTC, closed without merging